"""
test_shopify.py — Scratch script to test the ShopifyClient.
"""

import sys
import os

# Ensure backend root is on path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from utils.shopify_client import ShopifyClient, ShopifyAPIError

def main():
    print("Initializing ShopifyClient...")
    client = ShopifyClient()
    
    print("\n1. Testing Authentication & Location Fetching...")
    try:
        loc_id = client.get_primary_location()
        print(f"[OK] Primary Location ID: {loc_id}")
    except Exception as e:
        print(f"[FAIL] Failed to fetch location: {e}")
        return

    print("\n2. Testing Product Creation...")
    test_product_data = {
        "title": "BridgeBooks Test Book - Please Ignore",
        "body_html": "<strong>This is a test book</strong> generated by the API.",
        "vendor": "Test Publisher",
        "product_type": "Book",
        "variants": [
            {
                "price": "199.99",
                "sku": "TEST-ISBN-12345",
                "inventory_management": "shopify"
            }
        ]
    }
    
    try:
        product = client.create_product(test_product_data)
        product_id = product["id"]
        variant_id = product["variants"][0]["id"]
        inventory_item_id = product["variants"][0]["inventory_item_id"]
        print(f"[OK] Created Product ID: {product_id} (Variant: {variant_id})")
    except Exception as e:
        print(f"[FAIL] Failed to create product: {e}")
        return
        
    print("\n3. Testing Inventory Update...")
    try:
        inv = client.set_inventory(inventory_item_id, 42, loc_id)
        print(f"[OK] Set inventory to: {inv['available']}")
    except Exception as e:
        print(f"[FAIL] Failed to set inventory: {e}")
        
    print("\n4. Cleaning up (Deleting test product)...")
    try:
        client.delete_product(product_id)
        print("[OK] Test product deleted.")
    except Exception as e:
        print(f"[FAIL] Failed to delete product {product_id}: {e}")

if __name__ == "__main__":
    main()
